config/routes.rb
Rails.application.routes.draw do

  ### PAGINA INICIAL LOGIN ###
  root 'welcome#index'
  # root 'sessions#index'

  ### RESOURCES ###
  resources :users do
    get 'descarga_doc'
    get 'descarga_excel'
  end
  # get    '/login',   to: 'sessions#new' TODO: Si pasa tiempo y no se usa borrar
  post   '/login',   to: 'sessions#create' #Sirve para hacer submit en root
  delete '/logout',  to: 'sessions#destroy'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    if user.admin?
      can :create
      can :update
      can :destroy

    else

    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 4,message: "Max lo" }
  validates :email, presence: true, length: {maximum: 50 }
  validates :password,  presence: true, length: { maximum: 12 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :danger, :info, :log_warning_on_csrf_failure, :success
  include SessionsHelper
  before_action :require_login

  private

  def require_login
    unless logged_in?
      # flash[:error] = "You must be logged in to access this section"
      # redirect_to new_user_path if current_user.blank?# halts request cycle
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:index]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user, success: 'Welcome to Organizer-2018!'
    else
      # Create an error message.
      redirect_to :root, danger: 'Invalid email/password combination'

    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:index, :new]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new

  end

  def create
    @user = User.new(user_params)
    if @user.name.present? and @user.surname.present? and @user.email.present? and @user.password.present?
      @user.save
      byebug
      redirect_to @user, success: 'Registrado correctamente'
    else
      redirect_to new_user_path, info: 'Todos los campos son obligatorios'
    end
  end

  def descarga_doc
    require 'omnidocx'
    require 'caracal'
    # for e.g. if you had to merge two documents, just pass their entire paths in an array, if you need a page break in between documents then pass the page_break flag as true
    # Omnidocx::Docx.merge_documents(['/tmp/doc1.docx', '/tmp/doc2.docx'], '/tmp/output_doc.docx', true)
    @my_data = Hash.new
    @my_data[[1, 2]] = 23
    @my_data[[5, 6]] = 42
    Caracal::Document.save 'output_doc.docx' do |docx|
      docx.page_size do
        width 15840 # sets the page width. units in twips.
        height 12240 # sets the page height. units in twips.
        orientation :landscape # sets the printer orientation. accepts :portrait and :landscape.
      end
      docx.page_margins do
        left 720 # sets the left margin. units in twips.
        right 720 # sets the right margin. units in twips.
        top 1440 # sets the top margin. units in twips.
        bottom 1440 # sets the bottom margin. units in twips.
      end
      docx.page_numbers true do
        align :center
        label ''
      end

      docx.font name: 'Courier New'

      docx.style id: 'AltFont', name: 'altFont', font: 'Palatino'
      # page 1
      docx.h1 'Page 1 Header'
      docx.hr
      docx.p
      docx.h2 'Section 1'
      docx.p 'Lorem ipsum dolor....'
      docx.p
      docx.table @my_data, border_size: 4 do
        cell_style rows[0], background: 'cccccc', bold: true
      end

      # page 2
      docx.page
      docx.h1 'Page 2 Header'
      docx.hr
      docx.p
      docx.h2 'Section 2'
      docx.p 'Lorem ipsum dolor....'
      docx.ul do
        li 'Item 1'
        li 'Item 2'
      end
      docx.p
      docx.img 'google.png', width: 500, height: 300
    end


    send_file "output_doc.docx", :filename => "output_doc.docx", :type => 'application/docx'
  end

  def descarga_excel
    require 'create_excel'

    id_json = "Hola"
    Create_excel.new_excel_images(id_json)
    send_file "/tmp/fotos_arteris_excel.xlsx", :filename => "fotos_arteris_excel.xlsx", :type => 'application/xlsx'

  end

end

private

def user_params
  params.require(:user).permit(:name,:surname,:email, :password)
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :require_login, only: [:index]

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title First-app
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - flash.each do |message_type, message|
      %div(class="alert alert-#{message_type}" style="text-align:center;")= message
    = yield

app/views/users/index.html.haml
%h1 Listing users
%table
  %tr
    %th Mail
    %th
    %th
  - @users.each do |user|
    %tr
      %td= user.email
      %td= user.password
      %td
        %button= link_to 'Show', user_path(user)

app/views/users/new.html.haml
%body
  .user
    .user-container
      = form_with class:'form-user',scope: :user, url: users_path, local: true do |form|
        %p= "Registrate en Organizer-2018"
        %div
          = form.text_field :name, placeholder:"Nombre", type:"text"
        %div
          -#%br/
          = form.text_field :surname, placeholder:"Apellidos", type:"text"
        %div
          -#%br/
          = form.text_field :email, placeholder:"Correo electrónico", type:"email"
        %div
          -#%br/
          = form.text_field :password, placeholder:"Password", type:"password"
        %button(type="submit" name="commit" value="Iniciar" )
          = "Registrarme"

app/views/users/show.html.haml
.user
  .user-container
    %p
      %strong Nombre:
      = @user.name + ' ' + @user.surname
    %p
      %strong E-mail:
      = @user.email
    %p
      %strong Contraseña:
      = 'Cifrado'
    %div
      = link_to "DOC", user_descarga_doc_path(@user.id), :target => '_blank'
    %div
      = link_to "Excel", user_descarga_excel_path(@user.id), :target => '_blank'
    %div
      = link_to "SALIR", logout_path, method: :delete

app/views/welcome/index.html.haml
%body
  .hero
    .hero-container
      %h1.title
        Organizer-2018
      .badge
        %img(alt="img" src="/assets/badge.jpg")/
      .description
        %p
          Con esta aplicación puedes llevar la cuenta de las horas trabajadas por cada persona.
          Inicia sesión y lleva la cuenta de las horas.
      -#%form.form(action="/users" method="POST" )
      -#  %p Inicio sesión Organizer-2018
      -#  %input(placeholder="Correo electrónico" type="email")/
      -#  %input(placeholder="Password" type="text")/
      -#  %button(type="submit" name="commit") Comienza ahora

      = form_with class:'form', scope: :session, url: login_path, local: true do |form|
        %p= "Inicio sesión Organizer-2018"
        %div
          = form.text_field :email, placeholder:"Correo electrónico", type:"email"
        %div
          = form.text_field :password, placeholder:"Password", type:"password"
        %p
        %button(type="submit" name="commit" value="Iniciar" )
          = "Comienza ahora"
          -#= form.submit "Comienza ahora"
      .countdown
        %div Nuevo usuario? #{link_to "Registrate ya!", 'users/new', style:"color:gold;"}
        %br
        %p Propiedad de @rbn1993
        %p
          - now = DateTime.now
          %span= now.strftime("%H")+"h"
          %span= now.strftime("%M")+"m"